"""Add constraint profiles tables

Revision ID: 23416c89d0a9
Revises: ca4149cd5594
Create Date: 2026-02-28 10:49:30.634745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '23416c89d0a9'
down_revision: Union[str, None] = 'ca4149cd5594'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
