"""Add missing constraint tables

Revision ID: 72afe3621a32
Revises: 23416c89d0a9
Create Date: 2026-02-28 10:50:15.535546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '72afe3621a32'
down_revision: Union[str, None] = '23416c89d0a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_constraint_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('budget_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('time_available_months', sa.Integer(), nullable=True),
    sa.Column('weekly_bandwidth_hours', sa.Integer(), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=False),
    sa.Column('target_countries', sa.JSON(), nullable=False),
    sa.Column('excluded_countries', sa.JSON(), nullable=False),
    sa.Column('education_level', sa.String(length=50), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('visa_status', sa.String(length=50), nullable=True),
    sa.Column('citizenship_countries', sa.JSON(), nullable=False),
    sa.Column('commitment_level', sa.String(length=20), nullable=False),
    sa.Column('risk_tolerance', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_constraint_profiles_user_id'), 'user_constraint_profiles', ['user_id'], unique=True)
    op.create_table('opportunity_pruning_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('opportunity_id', sa.Uuid(), nullable=False),
    sa.Column('is_pruned', sa.Boolean(), nullable=False),
    sa.Column('pruning_reason', sa.String(length=50), nullable=True),
    sa.Column('violated_constraints', sa.JSON(), nullable=False),
    sa.Column('constraint_details', sa.JSON(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('constraint_score', sa.Float(), nullable=False),
    sa.Column('explanation_title', sa.String(length=200), nullable=True),
    sa.Column('explanation_detail', sa.Text(), nullable=True),
    sa.Column('pruning_algorithm_version', sa.String(length=20), nullable=False),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunity_pruning_logs_opportunity_id'), 'opportunity_pruning_logs', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_opportunity_pruning_logs_user_id'), 'opportunity_pruning_logs', ['user_id'], unique=False)
    op.create_table('constraint_feedback',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('pruning_log_id', sa.Uuid(), nullable=False),
    sa.Column('feedback_type', sa.String(length=20), nullable=False),
    sa.Column('feedback_detail', sa.Text(), nullable=True),
    sa.Column('suggested_constraints', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pruning_log_id'], ['opportunity_pruning_logs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_constraint_feedback_pruning_log_id'), 'constraint_feedback', ['pruning_log_id'], unique=False)
    op.create_index(op.f('ix_constraint_feedback_user_id'), 'constraint_feedback', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_constraint_feedback_user_id'), table_name='constraint_feedback')
    op.drop_index(op.f('ix_constraint_feedback_pruning_log_id'), table_name='constraint_feedback')
    op.drop_table('constraint_feedback')
    op.drop_index(op.f('ix_opportunity_pruning_logs_user_id'), table_name='opportunity_pruning_logs')
    op.drop_index(op.f('ix_opportunity_pruning_logs_opportunity_id'), table_name='opportunity_pruning_logs')
    op.drop_table('opportunity_pruning_logs')
    op.drop_index(op.f('ix_user_constraint_profiles_user_id'), table_name='user_constraint_profiles')
    op.drop_table('user_constraint_profiles')
    # ### end Alembic commands ###
