# Schema exports
from .token import (
    Token,
    TokenData,
    AuthRegisterRequest,
    AuthLoginRequest,
    AuthResponse,
    UserProfileResponse,
    UpdateProfileRequest,
    ChangePasswordRequest,
    ErrorResponse,
)

from .psychology import (
    PsychProfileBase,
    PsychProfileResponse,
    PsychProfileUpdate,
    PsychQuestionResponse,
    PsychQuestionListResponse,
    PsychAnswerRequest,
    PsychAnswerResponse,
    PsychSessionStartResponse,
    PsychSessionProgressResponse,
    PsychSessionCompleteResponse,
    PsychScoreHistoryResponse,
    PsychScoreHistoryListResponse,
    StartAssessmentRequest,
    SubmitAnswerRequest,
    AssessmentSummaryResponse,
)

from .route import (
    RouteTemplateResponse,
    RouteTemplateListResponse,
    RouteMilestoneTemplateResponse,
    RouteCreateRequest,
    RouteUpdateRequest,
    RouteResponse,
    RouteListResponse,
    RouteDetailResponse,
    RouteMilestoneUpdateRequest,
    RouteMilestoneResponse,
    AvailableTemplatesResponse,
)

__all__ = [
    # Auth schemas
    "Token",
    "TokenData",
    "AuthRegisterRequest",
    "AuthLoginRequest",
    "AuthResponse",
    "UserProfileResponse",
    "UpdateProfileRequest",
    "ChangePasswordRequest",
    "ErrorResponse",
    # Psychology schemas
    "PsychProfileBase",
    "PsychProfileResponse",
    "PsychProfileUpdate",
    "PsychQuestionResponse",
    "PsychQuestionListResponse",
    "PsychAnswerRequest",
    "PsychAnswerResponse",
    "PsychSessionStartResponse",
    "PsychSessionProgressResponse",
    "PsychSessionCompleteResponse",
    "PsychScoreHistoryResponse",
    "PsychScoreHistoryListResponse",
    "StartAssessmentRequest",
    "SubmitAnswerRequest",
    "AssessmentSummaryResponse",
    # Route schemas
    "RouteTemplateResponse",
    "RouteTemplateListResponse",
    "RouteMilestoneTemplateResponse",
    "RouteCreateRequest",
    "RouteUpdateRequest",
    "RouteResponse",
    "RouteListResponse",
    "RouteDetailResponse",
    "RouteMilestoneUpdateRequest",
    "RouteMilestoneResponse",
    "AvailableTemplatesResponse",
]
