"""Add user constraint profiles and deterministic pruning

Revision ID: ca4149cd5594
Revises: 0012
Create Date: 2026-02-28 10:45:18.012012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'ca4149cd5594'
down_revision: Union[str, None] = '0012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_job_queue', 'result_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('bookings', 'attachments',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_index('ix_credential_usage_tracking_event_type', table_name='credential_usage_tracking')
    op.alter_column('gap_analyses', 'missing_items',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('gap_analyses', 'missing_document_types',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('interview_answers', 'improvement_suggestions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('interview_answers', 'key_strengths',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('interview_feedback_templates', 'question_types',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('interview_feedback_templates', 'suggestions_en',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('interview_feedback_templates', 'suggestions_pt',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('interview_feedback_templates', 'suggestions_es',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('interview_feedback_templates', 'trigger_score_range',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('interview_feedback_templates', 'trigger_keywords',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('interview_questions', 'route_types',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('interview_questions', 'what_assessors_look_for',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('interview_questions', 'common_mistakes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('interview_sessions', 'question_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('interview_sessions', 'top_strengths',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('interview_sessions', 'improvement_areas',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('narrative_analyses', 'key_strengths',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('narrative_analyses', 'improvement_actions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('narrative_analyses', 'suggested_edits',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('narrative_analyses', 'raw_ai_output',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index('ix_narrative_analyses_version_id', table_name='narrative_analyses')
    op.alter_column('narratives', 'key_strengths',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('narratives', 'improvement_areas',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('opportunities', 'required_documents',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('opportunities', 'required_languages',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('opportunities', 'relevant_fields',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_index('ix_opportunities_competitiveness', table_name='opportunities')
    op.drop_index('ix_opportunities_opportunity_cost', table_name='opportunities')
    op.drop_column('opportunities', 'resource_requirements_score')
    op.drop_column('opportunities', 'target_salary')
    op.drop_column('opportunities', 'competitiveness_score')
    op.drop_column('opportunities', 'opportunity_cost_daily')
    op.drop_index('ix_opportunity_cost_widget_events_created_at', table_name='opportunity_cost_widget_events')
    op.drop_index('ix_opportunity_cost_widget_events_event_type', table_name='opportunity_cost_widget_events')
    op.alter_column('opportunity_matches', 'match_reasons',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('opportunity_matches', 'missing_requirements',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('prompt_execution_logs', 'input_variables',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('prompt_templates', 'slug',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('prompt_templates', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('prompt_templates', 'response_schema',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('prompt_templates', 'variables',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_index('ix_prompt_templates_slug', table_name='prompt_templates')
    op.create_unique_constraint(None, 'prompt_templates', ['slug'])
    op.drop_column('prompt_templates', 'description')
    op.alter_column('provider_profiles', 'education',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('provider_profiles', 'specializations',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('provider_profiles', 'target_regions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('provider_profiles', 'target_institutions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('provider_profiles', 'languages_spoken',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('provider_profiles', 'portfolio_links',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('provider_profiles', 'application_answers',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_constraint('uq_provider_profiles_user_id', 'provider_profiles', type_='unique')
    op.drop_index('ix_psych_answers_question_id', table_name='psych_answers')
    op.drop_index('ix_psych_answers_session_id', table_name='psych_answers')
    op.drop_index('ix_psych_assessment_sessions_status', table_name='psych_assessment_sessions')
    op.drop_index('ix_psych_assessment_sessions_user_id', table_name='psych_assessment_sessions')
    op.drop_index('ix_psych_questions_category', table_name='psych_questions')
    op.drop_index('ix_psych_questions_is_active', table_name='psych_questions')
    op.drop_index('ix_psych_score_history_created_at', table_name='psych_score_history')
    op.drop_index('ix_psych_score_history_user_id', table_name='psych_score_history')
    op.alter_column('readiness_assessments', 'gaps_identified',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('readiness_assessments', 'strengths',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('readiness_assessments', 'recommended_sprint_template_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_index('ix_route_milestone_templates_route_template_id', table_name='route_milestone_templates')
    op.drop_index('ix_route_milestones_route_id', table_name='route_milestones')
    op.drop_index('ix_route_milestones_status', table_name='route_milestones')
    op.drop_index('ix_route_templates_route_type', table_name='route_templates')
    op.drop_index('ix_route_templates_temporal_range', table_name='route_templates')
    op.drop_column('route_templates', 'recommended_temporal_range_max')
    op.drop_column('route_templates', 'recommended_temporal_range_min')
    op.drop_index('ix_routes_status', table_name='routes')
    op.drop_index('ix_routes_template_id', table_name='routes')
    op.drop_index('ix_routes_user_id', table_name='routes')
    op.drop_index('ix_scenario_simulations_user_id_created', table_name='scenario_simulations')
    op.alter_column('service_listings', 'includes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('service_listings', 'excludes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('service_listings', 'prerequisites',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('service_listings', 'deliverables',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_index('ix_service_listings_performance_bound', table_name='service_listings', postgresql_using='gin')
    op.drop_column('service_listings', 'performance_bound')
    op.drop_column('service_listings', 'performance_success_rate')
    op.alter_column('sprint_tasks', 'prerequisite_task_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('sprint_tasks', 'resource_links',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('sprint_templates', 'default_tasks',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('sprint_templates', 'suggested_resources',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('user_applications', 'checklist_progress',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index('ix_user_psych_profiles_temporal_preference', table_name='user_psych_profiles')
    op.drop_index('ix_user_psych_profiles_user_id', table_name='user_psych_profiles')
    op.drop_column('user_psych_profiles', 'temporal_preference_updated_at')
    op.drop_column('user_psych_profiles', 'temporal_preference')
    op.alter_column('user_sprints', 'name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('user_sprints', 'personalized_tips',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('user_sprints', 'linked_milestone_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.drop_index('ix_users_momentum_score', table_name='users')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'momentum_score')
    op.drop_column('users', 'last_momentum_check')
    op.drop_index('ix_verification_credentials_type', table_name='verification_credentials')
    op.drop_index('ix_verification_credentials_user_id_active', table_name='verification_credentials')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_verification_credentials_user_id_active', 'verification_credentials', ['user_id', 'is_active'], unique=False)
    op.create_index('ix_verification_credentials_type', 'verification_credentials', ['credential_type'], unique=False)
    op.add_column('users', sa.Column('last_momentum_check', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('momentum_score', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_index('ix_users_momentum_score', 'users', ['momentum_score'], unique=False)
    op.alter_column('user_sprints', 'linked_milestone_ids',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('user_sprints', 'personalized_tips',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('user_sprints', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.add_column('user_psych_profiles', sa.Column('temporal_preference', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('user_psych_profiles', sa.Column('temporal_preference_updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_index('ix_user_psych_profiles_user_id', 'user_psych_profiles', ['user_id'], unique=False)
    op.create_index('ix_user_psych_profiles_temporal_preference', 'user_psych_profiles', ['temporal_preference'], unique=False)
    op.alter_column('user_applications', 'checklist_progress',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('sprint_templates', 'suggested_resources',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('sprint_templates', 'default_tasks',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('sprint_tasks', 'resource_links',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('sprint_tasks', 'prerequisite_task_ids',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.add_column('service_listings', sa.Column('performance_success_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('service_listings', sa.Column('performance_bound', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_index('ix_service_listings_performance_bound', 'service_listings', ['performance_bound'], unique=False, postgresql_using='gin')
    op.alter_column('service_listings', 'deliverables',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('service_listings', 'prerequisites',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('service_listings', 'excludes',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('service_listings', 'includes',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.create_index('ix_scenario_simulations_user_id_created', 'scenario_simulations', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_routes_user_id', 'routes', ['user_id'], unique=False)
    op.create_index('ix_routes_template_id', 'routes', ['template_id'], unique=False)
    op.create_index('ix_routes_status', 'routes', ['status'], unique=False)
    op.add_column('route_templates', sa.Column('recommended_temporal_range_min', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('route_templates', sa.Column('recommended_temporal_range_max', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_index('ix_route_templates_temporal_range', 'route_templates', ['recommended_temporal_range_min', 'recommended_temporal_range_max'], unique=False)
    op.create_index('ix_route_templates_route_type', 'route_templates', ['route_type'], unique=False)
    op.create_index('ix_route_milestones_status', 'route_milestones', ['status'], unique=False)
    op.create_index('ix_route_milestones_route_id', 'route_milestones', ['route_id'], unique=False)
    op.create_index('ix_route_milestone_templates_route_template_id', 'route_milestone_templates', ['route_template_id'], unique=False)
    op.alter_column('readiness_assessments', 'recommended_sprint_template_ids',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('readiness_assessments', 'strengths',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('readiness_assessments', 'gaps_identified',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.create_index('ix_psych_score_history_user_id', 'psych_score_history', ['user_id'], unique=False)
    op.create_index('ix_psych_score_history_created_at', 'psych_score_history', ['created_at'], unique=False)
    op.create_index('ix_psych_questions_is_active', 'psych_questions', ['is_active'], unique=False)
    op.create_index('ix_psych_questions_category', 'psych_questions', ['category'], unique=False)
    op.create_index('ix_psych_assessment_sessions_user_id', 'psych_assessment_sessions', ['user_id'], unique=False)
    op.create_index('ix_psych_assessment_sessions_status', 'psych_assessment_sessions', ['status'], unique=False)
    op.create_index('ix_psych_answers_session_id', 'psych_answers', ['session_id'], unique=False)
    op.create_index('ix_psych_answers_question_id', 'psych_answers', ['question_id'], unique=False)
    op.create_unique_constraint('uq_provider_profiles_user_id', 'provider_profiles', ['user_id'])
    op.alter_column('provider_profiles', 'application_answers',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('provider_profiles', 'portfolio_links',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('provider_profiles', 'languages_spoken',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('provider_profiles', 'target_institutions',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('provider_profiles', 'target_regions',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('provider_profiles', 'specializations',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('provider_profiles', 'education',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.add_column('prompt_templates', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'prompt_templates', type_='unique')
    op.create_index('ix_prompt_templates_slug', 'prompt_templates', ['slug'], unique=True)
    op.alter_column('prompt_templates', 'variables',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('prompt_templates', 'response_schema',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('prompt_templates', 'tags',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('prompt_templates', 'slug',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.alter_column('prompt_execution_logs', 'input_variables',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('opportunity_matches', 'missing_requirements',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('opportunity_matches', 'match_reasons',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.create_index('ix_opportunity_cost_widget_events_event_type', 'opportunity_cost_widget_events', ['event_type'], unique=False)
    op.create_index('ix_opportunity_cost_widget_events_created_at', 'opportunity_cost_widget_events', ['created_at'], unique=False)
    op.add_column('opportunities', sa.Column('opportunity_cost_daily', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('opportunities', sa.Column('competitiveness_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('opportunities', sa.Column('target_salary', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('opportunities', sa.Column('resource_requirements_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_index('ix_opportunities_opportunity_cost', 'opportunities', ['opportunity_cost_daily'], unique=False)
    op.create_index('ix_opportunities_competitiveness', 'opportunities', ['competitiveness_score'], unique=False)
    op.alter_column('opportunities', 'relevant_fields',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('opportunities', 'required_languages',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('opportunities', 'required_documents',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('narratives', 'improvement_areas',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('narratives', 'key_strengths',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.create_index('ix_narrative_analyses_version_id', 'narrative_analyses', ['version_id'], unique=False)
    op.alter_column('narrative_analyses', 'raw_ai_output',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('narrative_analyses', 'suggested_edits',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('narrative_analyses', 'improvement_actions',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('narrative_analyses', 'key_strengths',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('interview_sessions', 'improvement_areas',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('interview_sessions', 'top_strengths',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('interview_sessions', 'question_ids',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('interview_questions', 'common_mistakes',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('interview_questions', 'what_assessors_look_for',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('interview_questions', 'route_types',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('interview_feedback_templates', 'trigger_keywords',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('interview_feedback_templates', 'trigger_score_range',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('interview_feedback_templates', 'suggestions_es',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('interview_feedback_templates', 'suggestions_pt',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('interview_feedback_templates', 'suggestions_en',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('interview_feedback_templates', 'question_types',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('interview_answers', 'key_strengths',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('interview_answers', 'improvement_suggestions',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('gap_analyses', 'missing_document_types',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('gap_analyses', 'missing_items',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.create_index('ix_credential_usage_tracking_event_type', 'credential_usage_tracking', ['event_type'], unique=False)
    op.alter_column('bookings', 'attachments',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('ai_job_queue', 'result_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
