services:
  - type: web
    name: olcan-compass-v25-test
    runtime: node
    plan: free
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NEXT_PUBLIC_DEMO_MODE
        value: true
      - key: DEMO_MODE
        value: true
      - key: NODE_ENV
        value: production
