# Schema exports
from .token import (
    Token,
    TokenData,
    AuthRegisterRequest,
    AuthLoginRequest,
    AuthResponse,
    UserProfileResponse,
    UpdateProfileRequest,
    ChangePasswordRequest,
    ErrorResponse,
)

from .psychology import (
    PsychProfileBase,
    PsychProfileResponse,
    PsychProfileUpdate,
    PsychQuestionResponse,
    PsychQuestionListResponse,
    PsychAnswerRequest,
    PsychAnswerResponse,
    PsychSessionStartResponse,
    PsychSessionProgressResponse,
    PsychSessionCompleteResponse,
    PsychScoreHistoryResponse,
    PsychScoreHistoryListResponse,
    StartAssessmentRequest,
    SubmitAnswerRequest,
    AssessmentSummaryResponse,
)

from .route import (
    RouteTemplateResponse,
    RouteTemplateListResponse,
    RouteMilestoneTemplateResponse,
    RouteCreateRequest,
    RouteUpdateRequest,
    RouteResponse,
    RouteListResponse,
    RouteDetailResponse,
    RouteMilestoneUpdateRequest,
    RouteMilestoneResponse,
    AvailableTemplatesResponse,
)

from .document import (
    DocumentCreate,
    DocumentUpdate,
    DocumentResponse,
    DocumentListResponse,
    DocumentSummary,
    PolishRequest,
    PolishResponse,
    PolishFeedback,
    DocumentTemplateResponse,
    TemplateListResponse,
)

from .dossier import (
    DossierCreate,
    DossierUpdate,
    DossierResponse,
    DossierSimpleResponse,
    DossierDocumentCreate,
    DossierDocumentUpdate,
    DossierDocumentInDossier,
    DossierTaskCreate,
    DossierTaskUpdate,
    DossierTaskInDossier,
)

from .application import (
    OpportunityBase,
    OpportunityCreate,
    OpportunityUpdate,
    OpportunityListItem,
    OpportunityDetailResponse,
    OpportunityListResponse,
    UserApplicationCreate,
    UserApplicationUpdate,
    UserApplicationListItem,
    UserApplicationDetailResponse,
    UserApplicationListResponse,
)

from .task import (
    TaskBase,
    TaskCreate,
    TaskUpdate,
    TaskResponse,
    TaskListResponse,
    SubTaskCreate,
    SubTaskUpdate,
    SubTaskResponse,
    UserProgressResponse,
    UserProgressUpdate,
    AchievementBase,
    AchievementResponse,
    UserAchievementResponse,
    AchievementListResponse,
    UserAchievementListResponse,
)

__all__ = [
    # Auth schemas
    "Token",
    "TokenData",
    "AuthRegisterRequest",
    "AuthLoginRequest",
    "AuthResponse",
    "UserProfileResponse",
    "UpdateProfileRequest",
    "ChangePasswordRequest",
    "ErrorResponse",
    
    # Psychology schemas
    "PsychProfileBase",
    "PsychProfileResponse",
    "PsychProfileUpdate",
    "PsychQuestionResponse",
    "PsychQuestionListResponse",
    "PsychAnswerRequest",
    "PsychAnswerResponse",
    "PsychSessionStartResponse",
    "PsychSessionProgressResponse",
    "PsychSessionCompleteResponse",
    "PsychScoreHistoryResponse",
    "PsychScoreHistoryListResponse",
    "StartAssessmentRequest",
    "SubmitAnswerRequest",
    "AssessmentSummaryResponse",
    
    # Route schemas
    "RouteTemplateResponse",
    "RouteTemplateListResponse",
    "RouteMilestoneTemplateResponse",
    "RouteCreateRequest",
    "RouteUpdateRequest",
    "RouteResponse",
    "RouteListResponse",
    "RouteDetailResponse",
    "RouteMilestoneUpdateRequest",
    "RouteMilestoneResponse",
    "AvailableTemplatesResponse",
    
    # Document schemas
    "DocumentCreate",
    "DocumentUpdate",
    "DocumentResponse",
    "DocumentListResponse",
    "DocumentSummary",
    "PolishRequest",
    "PolishResponse",
    "PolishFeedback",
    "DocumentTemplateResponse",
    "TemplateListResponse",
    
    # Dossier schemas
    "DossierCreate",
    "DossierUpdate",
    "DossierResponse",
    "DossierSimpleResponse",
    "DossierDocumentCreate",
    "DossierDocumentUpdate",
    "DossierDocumentInDossier",
    "DossierTaskCreate",
    "DossierTaskUpdate",
    "DossierTaskInDossier",
    
    # Application schemas
    "OpportunityBase",
    "OpportunityCreate",
    "OpportunityUpdate",
    "OpportunityListItem",
    "OpportunityDetailResponse",
    "OpportunityListResponse",
    "UserApplicationCreate",
    "UserApplicationUpdate",
    "UserApplicationListItem",
    "UserApplicationDetailResponse",
    "UserApplicationListResponse",
    
    # Task schemas
    "TaskBase",
    "TaskCreate",
    "TaskUpdate",
    "TaskResponse",
    "TaskListResponse",
    "SubTaskCreate",
    "SubTaskUpdate",
    "SubTaskResponse",
    "UserProgressResponse",
    "UserProgressUpdate",
    "AchievementBase",
    "AchievementResponse",
    "UserAchievementResponse",
    "AchievementListResponse",
    "UserAchievementListResponse",
]
